### ISSUE TITLE
[Theme Request] Misaka Mikoto

### ISSUE THREAD

**Issue by Unthrottled** [doki-theme/doki-master-theme#108]
## Who/What do you want to be featured?

[Misaka Mikoto](https://toarumajutsunoindex.fandom.com/wiki/Misaka_Mikoto) from Toaru Kagaku no Railgun

### What do they look like?

![Profile One](https://64.media.tumblr.com/421c3b13bcdd04e5b23a35f30532bb87/tumblr_nyoyqjd1AE1rmk3cyo1_500.gif)
![Profile Two](https://i.pinimg.com/originals/76/80/96/768096cf686d793efa72d5a0d14db06a.jpg)
![Profile Three](https://i1.sndcdn.com/avatars-TVcstS2AdckySuqe-FEAcDw-t500x500.jpg)

## What type of theme?

- [ ] Light Theme
- [ ] Dark Theme

## Additional Information (Optional)

Анон требует

**Comment by Exordio** [comment]
Thank you very much for all your work. The whole village is glad that we have you. lmao

**Comment by stanlee17** [comment]
i really need this :o
