### ISSUE TITLE
[Theme Request]  Izumi Sagiri(Eromanga Sensei)

### ISSUE THREAD

**Issue by sagirisense** [doki-theme/doki-master-theme#111]
## Who/What do you want to be featured?
Izumi Sagiri for Eromanga Sensei

### What do they look like?

![Adrenaline_Sagiri](https://user-images.githubusercontent.com/40755727/130733571-ebb561ce-3aba-4e1a-8584-8e2785a17a93.gif)
![thumb-1920-837706](https://user-images.githubusercontent.com/40755727/130733617-54096245-17b7-40b8-b7bd-239c7ac98b34.png)
![826363](https://user-images.githubusercontent.com/40755727/130733630-3def377a-b7bf-4672-be59-78dbad42d19e.png)

## What type of theme?

- [x] Light Theme
- [x] Dark Theme

## Additional Information (Optional)
You can use pink and gray as the main colors, but this is just a suggestion

**Comment by justalemon** [comment]
Suggestion: Light Theme uses the white shirt outfit, while Dark Theme uses the blue jacket outfit.

White outfit is the one shown above by @sagirisense, while the blue jacket outfit is this one:

![88086947_p0](https://user-images.githubusercontent.com/11861253/130763369-39f1cdb1-d112-4acd-a694-2ef09dd6ee49.jpg)
![image](https://user-images.githubusercontent.com/11861253/130763470-272cdc1d-2a92-47d9-a429-aed7463c4d95.png)

**Comment by justalemon** [comment]
Also, perhaps part of the "Love me Onii-san!" update?

**Comment by Unthrottled** [comment]
Thanks for saving me the trouble of having to create this issue!

I've been wanting to add Sagiri for a while now, and was planning on adding her in the next round of themes (once I get the time). I know what I want for the dark theme, because I like her dark jacket color. Will have to think about what the light theme looks like though.

**Comment by Unthrottled** [comment]
I am currently debating on whether I need another light theme or not, as there is going to be one in the coming release.

I've got the dark theme that I wanted, it will look a like this (I might change some things)

![Screenshot from 2021-09-16 07-23-55](https://user-images.githubusercontent.com/15972415/133612197-ae95e7bf-75f0-4dc4-8537-363b686646b9.png)


However, this is a very convincing & adorable argument

![Adrenaline_Sagiri](https://user-images.githubusercontent.com/40755727/130733571-ebb561ce-3aba-4e1a-8584-8e2785a17a93.gif)

I dunno, I'll see how I feel after I've completed the rest of the themes.
