### ISSUE TITLE
[Theme Request] Minaduki Shigure

### ISSUE THREAD

**Issue by Unthrottled** [doki-theme/doki-master-theme#112]
## Who/What do you want to be featured?

The last addition from NekoPara, [Shigure](https://nekopara.fandom.com/wiki/Shigure_Minaduki)

### What do they look like?

![Screenshot 2021-08-27 202557](https://user-images.githubusercontent.com/15972415/132111577-1bc4789b-a2f3-413a-924e-4f6c47cc0639.png)

![Screenshot 2021-08-27 202918](https://user-images.githubusercontent.com/15972415/132111629-60fda71b-b974-41bb-a411-f6e9acf726cc.png)

![Screenshot 2021-08-20 201419](https://user-images.githubusercontent.com/15972415/132111582-921b8b0e-8131-436b-b467-07ac9779927c.png)

![Screenshot 2021-08-13 204716](https://user-images.githubusercontent.com/15972415/132111586-9689f6e1-1b07-412f-9397-083a2c396450.png)

## What type of theme?

- [X] Light Theme

## Additional Information (Optional)

- **Pro**: Will create a Cat-Girl harem for you.
- **Con**: Is your little sister, by blood.

**Comment by justalemon** [comment]
> Is your little sister, by blood

Damn
