### ISSUE TITLE
[Theme Request] Senko (Sewayaki Kitsune no Senko-san)

### ISSUE THREAD

**Issue by madmod** [doki-theme/doki-master-theme#129]
## Who/What do you want to be featured?
Senko from Sewayaki Kitsune no Senko-san.

### What do they look like?
![Senko San](https://static.wikia.nocookie.net/p__/images/f/fb/Senkosan.jpg/revision/latest?cb=20190523181202&path-prefix=protagonist)
![Senko San](http://www.anime-evo.net/wp-content/uploads/2019/06/SSenko_10_1.jpg)
![Senko San](https://animerantshome.files.wordpress.com/2019/05/fox-01-01.png)
![Senko San](https://i.redd.it/hhbn23sapgs21.png)

## What type of theme?

- [X] Light Theme
- [ ] Dark Theme

## Additional Information (Optional)
Senko is the best! This description of the show explains why it is perfect for overworked programmers.

> Like many hardworking members of the workforce, Kuroto Nakano is perpetually stressed out by his job. Still, since he lives alone, he must carry on to sustain himself. Little do humans like Kuroto know, this stress takes the form of darkness residing within a person's body and will bring one's life to ruin. Fox deities can see this darkness and have the duty to save people before it is too late. To help rid Kuroto of his stress, Senko-san, an eight hundred-year-old foxgirl, volunteers to take care of him, and will do everything she can to ease the tension in his weary soul.

**Comment by Unthrottled** [comment]
There are times I wish I had a fox demigod to pamper me.

I would love to have a Senko Theme, but I only discovered her after I made a bunch of yellow themes and White & red themes.

![Maple](https://raw.githubusercontent.com/doki-theme/doki-theme-jetbrains/master/assets/screenshots/nekoPara/maple_light_code.png)
![best girl](https://raw.githubusercontent.com/doki-theme/doki-theme-jetbrains/master/assets/screenshots/franxx/zero_two_light_code.png)
![ishtar](https://raw.githubusercontent.com/doki-theme/doki-theme-jetbrains/master/assets/screenshots/fate/ishtar_light_code.png)
![Darkness](https://raw.githubusercontent.com/doki-theme/doki-theme-jetbrains/master/assets/screenshots/konoSuba/darkness_light_code.png)
![Tohru](https://raw.githubusercontent.com/doki-theme/doki-theme-jetbrains/master/assets/screenshots/dragonMaid/tohru_light_code.png)

If I come up with a unique way to create a theme based off of Senko, I'll add her. I'm going to try something new for some other themes, and maybe that might make a case to add Senko.

**Comment by akatsukilevi** [comment]
For Senko, it could be a dark based theme, like Megumin one, using Yellow as detail color
