### ISSUE TITLE
[Theme Request] CC - Code Geass

### ISSUE THREAD

**Issue by jamieeunice** [doki-theme/doki-master-theme#131]
## Who/What do you want to be featured?
I want C.C. (from Code Geas) to be featured.

### What do they look like?
<img src="https://static.wikia.nocookie.net/villains/images/9/9f/CC.png/revision/latest?cb=20190724014236"/>
<img src="https://pbs.twimg.com/media/D-98lESU4AA3nHN.jpg"/>

## What type of theme?

- [x] Light Theme
- [x] Dark Theme

## Additional Information (Optional)
She is very neon-y, and that would be too much for the eyes, so a light/medium green could work better for an editor. If the cheese plush toy she is always with could be features, that would be awesome.

**Comment by Unthrottled** [comment]
I like the Dark Purple/Burgundy combo of this outfit. 

<img src="https://static.wikia.nocookie.net/villains/images/9/9f/CC.png/revision/latest?cb=20190724014236"/>

Thank you for the suggestion!
