### ISSUE TITLE
[Theme Request] Rimuru Tempest

### ISSUE THREAD

**Issue by thecodewarrior** [doki-theme/doki-master-theme#143]
## Who/What do you want to be featured?
Rimuru Tempest (That Time I Got Reincarnated as a Slime)

### What do they look like?
[Episode 26 open (0:41)](https://beta.crunchyroll.com/watch/G2XU029GW/trade-with-the-animal-kingdom) - Nice Rimuru
[Episode 40 open (1:42)](https://beta.crunchyroll.com/watch/GMKUX54EQ/the-congress-dances) - Badass Rimuru
![image](https://user-images.githubusercontent.com/5467669/152073373-e620f5f0-ad99-40d7-ba9f-ff8cc346a570.png)

## What type of theme?

(probably one for nice and the other for badass/demon-lord Rimuru)
- [x] Light Theme
- [x] Dark Theme

## Additional Information (Optional)

1. They are best slime
2. Damn they be photogenic
3. In one month I binged through all 3,800 pages of the 12 volumes of the novel that have been translated so far
4. Again, he be best slime

**Comment by Unthrottled** [comment]
I was already planning making this theme later this year, thanks for saving me the hassle of making this issue!

**Comment by thecodewarrior** [comment]
I thought of it because I found [this image on DeviantArt](https://www.deviantart.com/dingier/art/Rimuru-Tempest-Tensei-shitara-Slime-Datta-Ken-789448598) while looking them up.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5467669/152076703-e06e4ec8-01e1-4df2-9d23-803ac4f55a99.png">

I don't expect you to make a ton of variants or anything, but having a version with his aura coming off him would probably look sweet.
