### ISSUE TITLE
[Theme Request] Yuzuriha Inori (+ Mana Ouma?)

### ISSUE THREAD

**Issue by cheiIy** [doki-theme/doki-master-theme#150]
## Who/What do you want to be featured?
   Yuzuriha Inori, [Guilty Crown's](https://anilist.co/anime/10793/GUILTY-CROWN/) main character,
   possbily comboed with Mana Ouma, GC's supporting character for a two-character theme.

### What do they look like?
[Inori's Anilist character page](https://anilist.co/character/43280/Inori-Yuzuriha)
[Inori's fandom wiki page](https://guiltycrown.fandom.com/wiki/Inori_Yuzuriha)
[Mana's Anilist character page](https://anilist.co/character/55165/Mana-Ouma)
[Mana's fandom wiki page](https://guiltycrown.fandom.com/wiki/Mana_Ouma)

<details>
<summary>Yuzuriha Inori</summary>
<img src="https://i.imgur.com/28HpFk3.jpg" alt="Inori_1">
<img src="https://i.imgur.com/6Xd7Ue5.png" alt="Inori_2">
<img src="https://i.imgur.com/79tEjHF.png" alt="Inori_3">
<img src="https://i.imgur.com/gNAO2uz.png" alt="Inori_4">
</details>
<details><summary>Mana Ouma</summary>
<img src="https://i.imgur.com/tWaWCYa.png" alt="Mana_1">
<img src="https://i.imgur.com/LizyGA4.jpg" alt="Mana_2">
<img src="https://i.imgur.com/JVSVsce.jpg" alt="Mana_3">
</details>

## What type of theme?

- [ ] Light Theme
- [x] Dark Theme

## Additional Information (Optional)
  The character's connection cannot be explained without some spoilers to the story, so I leave the explanation of that to the provided links.
  Personally I have a bit of a sentiment towards both the anime and the character, it being my second show watched, regardless of its mixed reception. Inori herself (and EGOIST's music) was the show's saving grace at the time and a pretty popular waifu. The collection is by no means running short of pink themes so I thought adding Mana for a two-character theme would bring in some uniqueness to the table.
  If you don't like that idea though, I really mostly care about Inori.

  Also, thank you for all the good work done.

**Comment by Unthrottled** [comment]
> The collection is by no means running short of pink themes

Yup, there's a whole bunch of pink haired anime girls, and therefore pink themes. So many!

> I thought adding Mana for a two-character theme would bring in some uniqueness to the table.

That's an interesting idea, though I don't know what I would do different with there color palette.

This image is neat:

![Mana](https://cosplayfu-website.s3.amazonaws.com/_Photo/character/mini/7073_1082.jpg)

However, that ☝️  color palette is kind of the same vibe I am planning for [Senjougahara's theme](https://bakemonogatari.fandom.com/wiki/Hitagi_Senjougahara)

I dunno, 🤷 

Anyways thanks for the suggestion and taking the time bring this to my attention.

**Comment by cheiIy** [comment]
`Yup, there's a whole bunch of pink haired anime girls, and therefore pink themes. So many!`
There really is something in that hair, huh.
`However, that ☝️ color palette is kind of the same vibe I am planning for [Senjougahara's theme](https://bakemonogatari.fandom.com/wiki/Hitagi_Senjougahara)`
Damn, them popular waifus always win.

**Comment by cheiIy** [comment]
`Yup, there's a whole bunch of pink haired anime girls, and therefore pink themes. So many!`
There really is something in that hair, huh.
`However, that ☝️ color palette is kind of the same vibe I am planning for [Senjougahara's theme](https://bakemonogatari.fandom.com/wiki/Hitagi_Senjougahara)`
Damn, them popular waifus always win.

As a matter of fact, Inori's also been then adapted as EGOIST's icon and persona for their vocalist during their later real life activities. They had support of her original designer - redjuice - which means you can also find her in some different color schemes:
<details><summary>White</summary>
<img src="https://i.imgur.com/xP8arkZ.jpg" alt="White_1">
<img src="https://i.imgur.com/kQ9d2NY.jpg" alt="White_2">
<img src="https://i.imgur.com/jFHGt8z.gif" alt="White_3">
</details>
<details><summary>Red/Black</summary>
<img src="https://i.imgur.com/NzkvO14.jpg" alt="RB_1">
<img src="https://i.imgur.com/Kvk1JaJ.jpg" alt="RB_2">
<img src="https://i.imgur.com/loPGFJx.jpg" alt="RB_4">
<img src="https://i.imgur.com/F18tHw3.jpg" alt="RB_3">
<img src="https://i.imgur.com/V1Fb0Dn.jpg" alt="RB_3_alt">
</details>
<details><summary>Or even orange</summary>
<img src="https://i.imgur.com/AfUfzCP.jpg" alt="Orange_1">
Her original suit was often rendered in more of an orange-ish fashion, than pure red:
<img src="https://i.imgur.com/BGxKlJ0.jpg" alt="Orange_2">
<img src="https://i.imgur.com/nvcf7Lq.png" alt="Orange_3">
</details>
<details><summary>A little extra</summary>
<img src="https://i.imgur.com/bR6PUX5.jpg" alt="Inori_Mana">
</details>

So in my opinion her color palette could offer some more elasticity than intially expected, though idk, I'm not the color designer here.
That's it for my attempt at convincing you, I did my best-ish. Thanks for consideration one way or another.

**Comment by Unthrottled** [comment]
> Damn, them popular waifus always win.

If you stick around till later this year, then it well make sense 😄 

That being said this looks amazing:

<img src="https://i.imgur.com/BGxKlJ0.jpg" alt="Orange_2">

Thanks for the ideas, We'll see how I feel later this year.
