### ISSUE TITLE
[Theme Request] Nakano Itsuki

### ISSUE THREAD

**Issue by Unthrottled** [doki-theme/doki-master-theme#162]
## Who/What do you want to be featured?

[The youngest Quint](https://5hanayome.fandom.com/wiki/Itsuki_Nakano)

### What do they look like?

![one](https://i.redd.it/peahlzqaetl61.png)
![two](https://files.yande.re/sample/67d194967e9ebdc4098b21864258d275/yande.re%20749508%20sample%205-toubun_no_hanayome%20cosplay%20kurokuro_illust%20nakano_ichika%20nakano_itsuki%20nakano_miku%20nakano_nino%20nakano_yotsuba%20yukata.jpg)
![three](https://i.ytimg.com/vi/8uxFgHTQNMs/maxresdefault.jpg)
![four](https://static1.cbrimages.com/wordpress/wp-content/uploads/2020/02/Itsuki-Smiling.jpg)

## What type of theme?

- [X] Light Theme

## Additional Information (Optional)

Itsuki, more like *Eat*suki... amirite?

**Comment by jibunnoeiko** [comment]
Have you seen this anime? What can you say? :3

**Comment by Unthrottled** [comment]
@jibunnoeiko 

I have it is in my 3x3 (my top ten favorites)! 

<details>
  <summary>My 3x3</summary>
  <img alt="3x3" src="https://raw.githubusercontent.com/Unthrottled/Unthrottled/main/3x3.png"/>
  
  #TeamNino #TeamOnoderaNasaki #TeamHimawari
</details>


I enjoyed both seasons of the anime. Futaro has his work cut out for him. When I eventually start reading Manga, I'll swing back to this series and see how it ends up (but I am pretty sure I know where it is going). Are you on team Itsuki?

**Comment by jibunnoeiko** [comment]
@Unthrottled 

I have not watched this anime yet, it often comes across on tik tok.  I think I'll take a look at the weekend :3
