### ISSUE TITLE
[Question] What is difference between 'id' and 'characterId'?

### ISSUE THREAD

**Issue by Dragon-0609** [doki-theme/doki-master-theme#171]
## What do you mean?
I mean, are they used for something? I don't see difference among them.

### Why do I ask?
At the moment I'm working on the Theme Downloader for my plugin. I wanted to use something like tokens, but found that 'id' and 'characterId' are never changed.

**Comment by Unthrottled** [comment]
`id` is the unique identifier for the specific theme where as `characterId` uniquely identifies the character the theme was based on. Example Zero Two, her light & dark theme have a different `id` but the same `characterId` [dark character id](https://github.com/doki-theme/doki-master-theme/blob/760d41c683554f6ebb9489a442cebe8964f05f35/definitions/franxx/zeroTwo/dark/zero.two.dark.master.definition.json#L85) and [light character id](https://github.com/doki-theme/doki-master-theme/blob/760d41c683554f6ebb9489a442cebe8964f05f35/definitions/franxx/zeroTwo/light/zero.two.light.master.definition.json#L82) are the same. 

I introduced these to support the FireFox's plugin settings menu.


<img width="441" alt="Screen Shot 2022-05-07 at 1 21 12 PM" src="https://user-images.githubusercontent.com/15972415/167266948-d3dc97b4-4836-45de-9510-424ad2801a78.png">


Hope that helps.
