### ISSUE TITLE
"Rimiru": typo or intentional?

### ISSUE THREAD

**Issue by AroLeaf** [doki-theme/doki-master-theme#198]
You consistently name Rimuru Tempest "Rimiru", and I was wondering, is this intentional or not?

**Comment by Unthrottled** [comment]
![Whoopsies](https://c.tenor.com/s0OCNrUXlCYAAAAC/oops-whoopsies.gif)

<sup><sup><sup>It wasn't intentional</sup></sup></sup>

**Comment by Unthrottled** [comment]
Thank you for bringing this to my attention. It will be hard to break the muscle memory of typing Rimiru.
