### ISSUE TITLE
Clarify Copyright License

### ISSUE THREAD

**Issue by lovelyyfiaaa** [doki-theme/doki-master-theme#199]
Hiiiii! <3

It appears this repository does not have any information on the source code and colors copyright or have any copies of copyright licenses. Soo, can I ask to have them available here?

The `package.json` file does contain the license `MIT` to be set, but given it's the default license set by NPM, I'm not sure if it's valid..

**Comment by Unthrottled** [comment]
Hey! Thanks for bringing this to my attention. The [rest of my stuff is under the MIT license](https://github.com/doki-theme/doki-theme-jetbrains/blob/master/LICENSE), so I just took a license file from there. Thanks!

**Comment by lovelyyfiaaa** [comment]
Aaa thank youu!!

I'm making my own theme based on Natsuki Light theme, so thank you soo much! <3
