### ISSUE TITLE
[Theme Request] 

### ISSUE THREAD

**Issue by paulo-grechi** [doki-theme/doki-master-theme#202]
## Who/What do you want to be featured?

Zero Two's Dark Obsidian Theme from VSCode on Intellij

### What do they look like?

same stuff from VSCode's Dark Obisidian theme for Zero Two

## What type of theme?

- [ ] Light Theme
- [ x] Dark Theme

**Comment by Unthrottled** [comment]
I am a bit confused.

![Zero Two Obsidian](https://raw.githubusercontent.com/doki-theme/doki-theme-jetbrains/master/assets/screenshots/franxx/zero_two_obsidian_code.png)

[Version v88.1-1.4.0](https://plugins.jetbrains.com/plugin/10804-the-doki-theme/versions/stable/205763) is available right now. You might need to update your IDE, to support the latest update (I'm not going to support older platforms). [See these install instructions if that doesn't help](https://github.com/doki-theme/doki-theme-jetbrains#installation)

I'll close the issue for the time being, we can discuss if I misunderstood.
