### ISSUE TITLE
[Theme Request] Marin Kitigawa

### ISSUE THREAD

**Issue by MaximumEffort03** [doki-theme/doki-master-theme#207]
## Who/What do you want to be featured?
Marin Kitigawa

### What do they look like?
![image](https://user-images.githubusercontent.com/114207541/191998364-b429f9a7-518b-4ee5-a47d-be4a021c9add.png)
Thats what she looks like but if you search her up you would find plenty of images for her

## What type of theme?

- [ ] Light Theme
- [x] Dark Theme

## Additional Information (Optional)
 Marin is an S Tier waifu She is built different in the good way. Best Girl of 2022

**Comment by Unthrottled** [comment]
Ah yes, Marin is top-tier, she's already got a request #148 submitted. I really enjoyed My Dress Up Darling, so she has a higher chance of getting in. 

Imma close this since it's a duplicate, thanks!

**Comment by MaximumEffort03** [comment]
Okay thank you so much!!
