### ISSUE TITLE
Wallpaper assets access

### ISSUE THREAD

**Issue by andrewbaay** [doki-theme/doki-master-theme#219]
**Is your feature request related to a problem? Please describe.**
This is a feature request and is not related to a problem.

**Describe the solution you'd like**
I would like to have access to wallpapers used on Doki theme to theme other applications this theme pack does not support.

**Describe alternatives you've considered**
finding the assets themselves

**Comment by Unthrottled** [comment]
https://github.com/doki-theme/doki-theme-assets/tree/master/backgrounds/wallpapers
☝️  Here you go

I think I've linked it in the READMEs of the projects, but I'll do a better job of making it more visible.
