### ISSUE TITLE
[Theme Request] Iwakura Lain

### ISSUE THREAD

**Issue by Kekekke** [doki-theme/doki-master-theme#221]
## Who/What do you want to be featured?
 Lain Iwakura,

### What do they look like?

![88005553535](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKcoJpOI2Sy_TNduVbKCm2r4qWnkWs6_vZUg&usqp=CAU)
![123323123](https://media.tenor.com/1_YZPyzEOAEAAAAC/lain-serial-experiments-lain.gif)
![5763573-serial-experiments-lain-wallpapers](https://user-images.githubusercontent.com/41847420/209538750-8884915b-f77b-459b-8108-8a86a4698cf8.jpeg)

## What type of theme?

- [ +] Light Theme
- [ +] Dark Theme

## Additional Information (Optional)

It is literally the Goddess of Wire,  all praise Lain

**Comment by Unthrottled** [comment]
Closing because duplicate you can follow progress on #146 

I've got her lined up next, just haven't felt the need to add new themes yet. Thanks!
