### ISSUE TITLE
[Theme Request] Nezuko Kamado

### ISSUE THREAD

**Issue by SilverDeus** [doki-theme/doki-master-theme#228]
Who/What do you want to be featured?
Nezuko Kamado from Demon Slayer

What do they look like?
https://www.pinterest.fr/pin/2111131069007358/
https://www.pinterest.fr/pin/192740059045508700/
https://www.pinterest.fr/pin/590604938646704878/
https://www.pinterest.fr/pin/1007117535397498353/
https://www.pinterest.fr/pin/51580358222633874/

What type of theme?

- [x] Light Theme
- [x] Dark Theme

**Comment by Unthrottled** [comment]
Duplicate of #47
