### ISSUE TITLE
[Theme Request] Umi Sonoda from Love Live!

### ISSUE THREAD

**Issue by Virepri** [doki-theme/doki-master-theme#34]
## Who/What do you want to be featured?

I would like to see Umi Sonoda from Love Live! featured.

### What do they look like?

![](https://img2.gelbooru.com//images/28/2e/282ed20d78a2b925d55acb23ee56e693.jpg)

Sticker wise, many a good chibi umi already exist!

![](https://i.schoolido.lu/chibi/Umi_China.png)
![](https://i.pinimg.com/originals/c9/bb/85/c9bb85ba78a113c63632ba70efd37610.png)

## What type of theme?

- [ ] Light Theme
- [x] Dark Theme

## Additional Information (Optional)

  
[May her love arrow shoot into your heart](www.youtube.com/watch&v=dCmb_eqx9aU&feature=emb_title)

**Comment by Virepri** [comment]
Coloring wise, I think something similar to Vivaldi's private window theming could work well.
![image](https://user-images.githubusercontent.com/13892402/102513095-a5942980-403f-11eb-8d56-bfbe443b8bcf.png)

**Comment by Unthrottled** [comment]
> I think something similar to Vivaldi's private window theming could work well

That does look nice. I'll have to do some more research for a color palette, but yeah, it will most likely be something similar to that.

**Comment by Unthrottled** [comment]
Hey friend! Thank you for the suggestion. I think Umi is going to be a great addition! I feel her theme came out nice (thanks for the giving me a color to anchor to).

Just a sneak peek of what to expect

![umi_dark_code](https://user-images.githubusercontent.com/15972415/103234938-7bc3e800-4906-11eb-9968-ce26acccbfc2.png)

So I don't plan on publishing this release (to the JetBrains marketplace) right away. I want to test drive the themes for a bit, and work out the small issues. [Once this pull request](https://github.com/doki-theme/doki-theme-jetbrains/pull/298) is merged, I _will_ publish the release to my [canary release](https://github.com/Unthrottled/jetbrains-plugin-repository#canary) channel.
