### ISSUE TITLE
[Theme Request] Jabami Yumeko

### ISSUE THREAD

**Issue by Unthrottled** [doki-theme/doki-master-theme#41]
## Who/What do you want to be featured?

[Jabami Yumeko](https://kakegurui.fandom.com/wiki/Yumeko_Jabami) from Kakegurui - Compulsive Gambler

### What do they look like?

![Profile One](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/bfdf36ee-9707-4809-8f87-67b882950b82/dcis3u6-dbc1cb92-1937-4a45-a751-c55990f3218f.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvYmZkZjM2ZWUtOTcwNy00ODA5LThmODctNjdiODgyOTUwYjgyXC9kY2lzM3U2LWRiYzFjYjkyLTE5MzctNGE0NS1hNzUxLWM1NTk5MGYzMjE4Zi5qcGcifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.T_62ppFeG6yVzdkxmjKNkep8BLs-e9UTVNxykabSh7k)

![Profile Two](https://c4.wallpaperflare.com/wallpaper/228/1/282/erominimalistsensei-jabami-yumeko-kakegurui-minimalism-wallpaper-preview.jpg)

![Profile Three](https://static.wikia.nocookie.net/kakegurui/images/1/18/YumekoNewprofile.jpg/revision/latest?cb=20190712210508)

## What type of theme?

- [X] Dark Theme

## Additional Information (Optional)

  
[I think this about sums it up](https://youtu.be/9lIu9iJ0njU?t=13) (should probably listen with headphones :wink: )

**Comment by Bismuth10K** [comment]
Hey 

I was wondering if you have any release date please ?

Have a nice day.
Bismuth

**Comment by Unthrottled** [comment]
@Bismuth10K Excellent question. I am currently working on [v10](https://github.com/doki-theme/doki-master-theme/milestone/4) at the moment. Which will be done in the next week or two.

I haven't planned [v11](https://github.com/doki-theme/doki-master-theme/milestone/5) yet.
So if she makes it into that release, probably Late May, Early June. Thanks for the interest!

**Comment by Bismuth10K** [comment]
Nice. 
I love jabami yumeko, that is why i'm so happy ! And i try to convince my friends to code thanks to your plugin Haha

**Comment by Unthrottled** [comment]
@Bismuth10K So if you are still using my themes, then you've got something to look forward to in the coming weeks. If not, no big deal, Yumeko is a great addition none the less :smile: 

![Screenshot from 2021-06-04 05-28-57](https://user-images.githubusercontent.com/15972415/120788643-2e235b00-c4f6-11eb-9dff-40c7bef1ca2d.png)

**Comment by Bismuth10K** [comment]
Oh boy, I love it !
I don't what i could say or recommand you. 
Thanks you for the news.
