### ISSUE TITLE
[Theme Request] Tomori Nao

### ISSUE THREAD

**Issue by Leplik500** [doki-theme/doki-master-theme#48]
## Who/What do you want to be featured?
Tomori Nao from anime "Charlotte"

### What do they look like?
![image](https://user-images.githubusercontent.com/51443060/109419055-8ff69500-79dc-11eb-8145-41f4d9a98f76.png)
![image](https://user-images.githubusercontent.com/51443060/109429892-69058680-7a0f-11eb-8add-b3de13f56ef8.png)
![image](https://user-images.githubusercontent.com/51443060/109429917-8b979f80-7a0f-11eb-8fd4-6f5f48d1f181.png)

## What type of theme?
Both
- [x] Light Theme

- [x] Dark Theme

**Comment by Unthrottled** [comment]
I was wondering when she was going to show up! I've actually got Charlotte in my watch queue. (I'll eventually get to it!). :thinking: I'll need to do some thinking on what color palette I'l want. She is cute, so there is a chance she may make it with the others.

> - [x] Adding `x` between the `[ ]` checks the box
- [x] Adding `x` between the `[ ]` checks the box
