### ISSUE TITLE
[Theme Request] Miku Nakano from The Quintessential Quintuplets

### ISSUE THREAD

**Issue by crazygmr** [doki-theme/doki-master-theme#50]
## Who/What do you want to be featured?
Miku Nakano from The Quintessential Quintuplets

### What do they look like?
![Miku Picture - 1](https://user-images.githubusercontent.com/48188550/110514723-358cc100-80cd-11eb-8f06-926621d4262b.jpg)
![Miku Picture - 5](https://user-images.githubusercontent.com/48188550/110514750-3c1b3880-80cd-11eb-8c27-02198348098d.jpg)
![Miku Picture - 10](https://user-images.githubusercontent.com/48188550/110514784-45a4a080-80cd-11eb-814e-7f3096f7a4ec.jpg)

  
[https://5hanayome.fandom.com/wiki/Miku_Nakano](url)

## What type of theme?

- [ ] Light Theme
- [x] Dark Theme

## Additional Information (Optional)
Not only is she best girl and my number 1 waifu, I love her shade of blue and would love to have that in IDE
https://www.youtube.com/watch?v=diYudKyhL3Q

**Comment by Unthrottled** [comment]
Ah! 

I remember this was the first image I saw of her

![Miku](https://ih1.redbubble.net/image.775352145.3597/flat,750x,075,f-pad,750x1000,f8f8f8.jpg)

> Is she cute? 

Yes!

> Do I need another blue theme? 

Maybe?

> Will I keep her in mind for the next round?

Yes. 

I do have my eyes on [Artoria Pendrangon, tho](https://static.wikia.nocookie.net/deathbattlefanon/images/5/53/Saber_arturia-0.png/revision/latest/scale-to-width-down/266?cb=20160312035033)


Thank you for the suggestion!

**Comment by Unthrottled** [comment]
![Screenshot from 2021-04-26 18-07-34](https://user-images.githubusercontent.com/15972415/116161993-7612bf00-a6ba-11eb-8cba-8a72ee31049d.png)

@crazygmr This is what I got :point_up: 
Expect a release in the coming weeks. Thanks for the suggestion!

<sub><sub>BTW, Nino is best girl :smile: </sub></sub>
