### ISSUE TITLE
[Theme Request] Yuno Gasai

### ISSUE THREAD

**Issue by Yonwabisa** [doki-theme/doki-master-theme#51]
## Who/What do you want to be featured?

 [Yuno Gasai]( https://futurediary.fandom.com/wiki/Yuno_Gasai#Personality
), from Mirai Nikki

### What do they look like?

![Profile One](https://www.anime-planet.com/images/characters/yuno-gasai-10078.jpg)
![Profile Two](https://ih1.redbubble.net/image.396989355.7769/flat,750x1000,075,f.u1.jpg)

## What type of theme?

- [ ] Light Theme
- [X] Dark Theme

## Additional Information (Optional)

Does your editor/IDE predict what you're trying to type?
Well Yuno kinda does too, this waifu knows every single thing you're doing,
and going to do.
With Yuno, It's just you, your waifu, and your code... No bug can stand between you!
This is a tier S waifuuuu!!!

**Comment by Unthrottled** [comment]
The danger waifu. Very interesting choice friend!

If I am going to add her, she'll be going in with [Jabami Yumeko](https://github.com/doki-theme/doki-master-theme/issues/41)

**Comment by Unthrottled** [comment]
@Yonwabisa If you are still using my themes, then you've got something to look forward to in the coming weeks. If not, no worries, I've now got a nice yandere addition now :smile: 

Thank you for the suggestion!

![Screenshot from 2021-06-02 06-15-34](https://user-images.githubusercontent.com/15972415/120471376-40708e00-c36a-11eb-8132-edee89dd56ce.png)

**Comment by Yonwabisa** [comment]
I am still using your themes, and that looks amazing, can't wait
