### ISSUE TITLE
[Theme Request] Hayase Nagatoro

### ISSUE THREAD

**Issue by HjalmarThulstrup** [doki-theme/doki-master-theme#54]
## Who/What do you want to be featured?
Hayase Nagatoro

### What do they look like?
Nagatoro is a very tan girl, because she likes sports (swimming) and is often outside. Always has tan lines from wearing a one-piece swimsuit outdoors.
Here's the [wiki](https://nagatoro.fandom.com/wiki/Hayase_Nagatoro) of the character

![Image One](https://i1.wp.com/www.otaquest.com/wp-content/uploads/2021/01/36A2C570-A472-46F1-B6C0-C36E9F099BCD.jpeg?resize=640%2C358&ssl=1)
![Image Two - from upcoming anime of the manga](https://www.otakutale.com/wp-content/uploads/2020/12/Ijiranaide-Nagatoro-san-TV-Anime-Visual-02.jpg)
![Image Three](https://static.myfigurecollection.net/pics/figure/big/935385.jpg)

## What type of theme?

- [ ] Light Theme
- [x] Dark Theme

## Additional Information (Optional)
Nagatoro is hands down best girl, she deserves her own Doki theme. She is also very popular character at the moment because she is getting her own anime this spring.

**Comment by Unthrottled** [comment]
Tan girls are nice! Haven't seen much on this show, but I knew of its existence. 
I see those two hair clips and immediately think of Mai Sakurajima. Thanks for the suggestion!

**Comment by Unthrottled** [comment]
@HjalmarThulstrup If you are still using my themes, then you have something to look forward to in the coming weeks. If not, no worries, I think she's still a good addition to my collection. 

![Screenshot from 2021-06-07 18-30-03](https://user-images.githubusercontent.com/15972415/121100243-0ca8c480-c7bf-11eb-8643-a4f57b6e5474.png)

Kinda wish I watched the anime so I could have derived a more accurate look and feel :shrug: 

It will look something a bit like that.

Thanks for the suggestion!
