### ISSUE TITLE
[Sticker submission] Miku by Puti Devil.

### ISSUE THREAD

**Issue by JohnEdwa** [doki-theme/doki-master-theme#62]
The default Miku sticker didn't really tickle my fancy, so I made my own using an artwork by [ぷちでびる aka Puti Devil](https://www.pixiv.net/en/users/7241) I've loved for well over a decade. Thought that I might as well plop it here, if you happened to want to add it in officially.   

I couldn't find the official source for the version I used, [only the repainted one](https://www.pixiv.net/en/artworks/1388701), so the best I can give is [this Konachan post](https://konachan.com/post/show/27922/gray-hatsune_miku-puti_devil-vocaloid).

![miku](https://user-images.githubusercontent.com/5417183/114064598-52adde80-9889-11eb-9eb1-1b017ca0f9a0.png)

**Comment by JohnEdwa** [comment]
A vectorized version of this same image [exists on Deviantart](https://www.deviantart.com/bogskiii/art/Hatsune-Miku-Vector-121995023), but I'm not sure if using the same thing twice is the best course of action. Guess it's a fair backup solution. 
Otherwise, my experience with the minimalistic vectorized style is limited to a hazy memory of 15 year old anime iPod memes from 4chan, so I can't be much help there. I have no clue what images look good converted to that style.

**Comment by Unthrottled** [comment]
> but I'm not sure if using the same thing twice is the best course of action

Yeah I don't really care to do that.

> I have no clue what images look good converted to that style

I guess I was just looking for any art in general. If I like it and think it has potential, I'll take a bit of create freedom and make something that looks nice (to me at least). Was kind of hoping you knew of a good Miku image, was what I was trying to get at.

<details>
<summary>Exhibit A</summary>

| Before | After |
| --- | --- |
| ![68907767_p0_master1200](https://user-images.githubusercontent.com/15972415/114102293-abcb4180-988c-11eb-8277-c05aa5366c50.jpg) | ![zero_two_dark](https://user-images.githubusercontent.com/15972415/114102688-678c7100-988d-11eb-9edb-93b4ce1df685.png) |

</details>

**Comment by JohnEdwa** [comment]
Hmh. I went for a scavenge hunt, [ended up with this one (possibly) from Kuroi.](https://danbooru.donmai.us/posts/1985749) Also ended up with a whole load of new wallpapers for myself, but [their general style](https://user-images.githubusercontent.com/5417183/114278675-6f304f00-9a20-11eb-8c5c-42c8f1640077.JPG) should prove fairly well why I'm not the best person to try looking for clean and simple backgrounds :)

But in any case, as I can't really do the vectorizing thing, I just used "Mean Curvature Blur" in GIMP to simplify it a bit, which I think ended up working fairly well: 
![image](https://user-images.githubusercontent.com/5417183/114279103-77898980-9a22-11eb-8c21-72ab1a19a6da.png)


---


I also noticed that for some reason, Visual Studio Code is very bad at handling transparency. 
The same image saved at the same 8% layer opacity, except there is a squiggly background colour on the right ([i.e like this](https://user-images.githubusercontent.com/5417183/114279463-55910680-9a24-11eb-8204-47b5a26e5548.png)), has [terrible colour banding on the parts that are transparent.](https://user-images.githubusercontent.com/5417183/114279491-81ac8780-9a24-11eb-9037-75a29820e14a.png)  Not sure if there is anything one can do here - if the background isn't transparent, then it will work with only one theme colour...

**Comment by Unthrottled** [comment]
>  as I can't really do the vectorizing thing

Sorry for not being clear. I was asking for reference images, because I was going to do that work. It's something I enjoy doing.

> except there is a squiggly background colour on the right (i.e like this)

Either I am missing something, but I cannot see the issue in any of the vs code pictures you posted. 

---

So I like the image you posted, them thighs are thicc.

I did my own digging too

I think this one would be nice, having Miku hang out with you as you code

![One](https://cdn.donmai.us/sample/7b/b3/__hatsune_miku_vocaloid_drawn_by_shuzi__sample-7bb3fef945a269ef40d92f7d87494072.jpg)

This one gives off the same vibes as the existing wallpaper, which is nice

![Two](https://danbooru.donmai.us/data/original/3a/76/__hatsune_miku_vocaloid_drawn_by_tokki__3a76f939ef8c468d0ff3e68a0f325158.png)

I just liked this one

![Three](https://danbooru.donmai.us/data/sample/17/6a/__hatsune_miku_vocaloid_and_1_more_drawn_by_mossi__sample-176ae96420c7353b29c37e074ca7d821.jpg)

**Comment by JohnEdwa** [comment]
>Sorry for not being clear. I was asking for reference images, because I was going to do that work. It's something I enjoy doing.

Ah, no worries, I understood you perfectly. I would have just preferred to do a mockup in that style if I could have, to better see how it would look. But as I can't I tried something a bit similar, which was to blur it a bit so that the smaller details are removed.

>Either I am missing something, but I cannot see the issue in any of the vs code pictures you posted.

If you open these two on separated tabs and switch between them, it's obvious as day and night. Again, same image at 8% opacity but one is a transparent PNG white the other one has been merged in GIMP with a background of the same colour that the theme has.

[_color_bg](https://user-images.githubusercontent.com/5417183/114284956-0dcda780-9a43-11eb-8f2c-3fa255b811f3.png)
[_transparent_bg](https://user-images.githubusercontent.com/5417183/114284954-0c9c7a80-9a43-11eb-8343-ee9bd6e82611.png)

Another thing I noticed is that unless the image is transparent, [the theme making it darker for the code window doesn't work.](https://user-images.githubusercontent.com/5417183/114286403-e4664900-9a4d-11eb-80f0-82806bb0799f.png) Also breaks showing the full colour image, as [the (usually) transparent BG is always drawn over it.](https://user-images.githubusercontent.com/5417183/114286523-0ca27780-9a4f-11eb-99f7-ab04eace35e9.png)

 
That said, with the flat shaded vectorized images none of this is really an issue.


---

> I did my own digging too

I vote no for the angery miku (even though [the song the artwork is referencing](https://www.youtube.com/watch?v=SmX5cnQ1YAg) is probably one of my favourites) and cast my vote for the second one, but the first is really cute too. I'll most likely continue to use the one I found with the edits I've done to it myself, but you've found very good choices too. Take your pick, what you think would fit the best.

**Comment by Unthrottled** [comment]
Aight, so I got lost during our whole "VS Code Glass Pane Wallpaper Issue".
Though it sounds to me like, you got it where you wanted it to, and know enough to goof around with VSCode's CSS. 

Just as a heads up, if you are just replacing the image installed by the plugin (Like the same path) then it will probably be overwritten in the future. I have code that enables me to make updates to images without having users update the plugin. So you probably want to change the CSS to point at a file not at that path.

Thanks for the suggestion and talking with me about Miku!

I'll close this issue whenever I [complete v10.0.0](https://github.com/doki-theme/doki-master-theme/milestone/4)

**Comment by JohnEdwa** [comment]
>I have code that enables me to make updates to images without having users update the plugin. So you probably want to change the CSS to point at a file not at that path.

That would indeed be the correct way. 
But the lazy way is to just make the miku.png files Read Only :P

I'll take this opportunity to mention that it would be neat if there was a built in way to install a custom wallpaper and sticker instead of having to edit the CSS. I guess the quickest would be to create a "Install Custom Wallpaper" script that would point the CSS to a local file, and then leave it out of the update script. 

In any case, huge thanks for making the project as without it I would have never even realized my code editor could be weebified.

**Comment by Unthrottled** [comment]
Sounds like you have a use case for [vscode-background](https://github.com/shalldie/vscode-background) which does almost what the Doki-Theme does, but I think it's just limited to the editor window and you can do the custom image thing. I imagine it could be tweaked a bit to cover the entire window (you have the CSS from the Doki theme VS Code to give you a boost).

**Comment by JohnEdwa** [comment]
Yeah I took a look at that, but this modified DT solution works well for me too.

One bug I noticed though, the bracket pairing highlight is black on dark and white on light Doki-Themes: 
![themes](https://user-images.githubusercontent.com/5417183/114289014-14204b80-9a64-11eb-8ecf-b41fe74713d0.png)

**Comment by Unthrottled** [comment]
Cool I just fixed that on the JetBrains Plugin, I just used the theme's accent color.

For example here is Miku's

![image](https://user-images.githubusercontent.com/15972415/114289396-2a66e100-9a3d-11eb-935d-4beee6bcee1a.png)

**Comment by Unthrottled** [comment]
![sample_1f59d66227c5539c52f9776c64b49946d6ba7059 (1)](https://user-images.githubusercontent.com/15972415/116163515-85473c00-a6bd-11eb-89bd-92c9d089d787.jpg)

I changed my mind, I want this. (There is soooooooooo much Hatsune Miku art). Am disappointed that I'll have draw her hair band square things, or whatever the technical term is.

I'm also going to probably change up some of her themes colors (nothing too drastic).

**Comment by Unthrottled** [comment]
Well that took longer than I would have liked. I regret choosing art that is highly detailed.

I also updated her syntax coloring a bit (The html, string, & comments) colors.

| Before | After |
| --- | --- |
| ![Screenshot from 2021-04-30 18-20-43](https://user-images.githubusercontent.com/15972415/116763637-b8523e00-a9e3-11eb-978e-54619ab47499.png) | ![Screenshot from 2021-04-30 18-34-25](https://user-images.githubusercontent.com/15972415/116763645-be481f00-a9e3-11eb-8054-0d3474d10c3e.png) |


Thank you for the suggestion, I look forward to coding with Hatsune Miku again.
