### ISSUE TITLE
[Theme Request] K-On Best Girl(s)

### ISSUE THREAD

**Issue by plawanjyoti** [doki-theme/doki-master-theme#66]
## Who/What do you want to be featured?
All the girls from K-On

### What do they look like?
![image](https://user-images.githubusercontent.com/41319398/114444665-c4b95700-9bec-11eb-9b79-904e30da13eb.png)
![image](https://user-images.githubusercontent.com/41319398/114444943-13ff8780-9bed-11eb-8f6d-b66ff2865b8d.png)
![image](https://user-images.githubusercontent.com/41319398/114444969-1d88ef80-9bed-11eb-80fc-d3b00d3345e9.png)
![image](https://user-images.githubusercontent.com/41319398/114445003-2a0d4800-9bed-11eb-9a25-23dd6d6b401c.png)

## What type of theme?

- [ ] Light Theme
- [ ] Dark Theme
- [x] Both

## Additional Information (Optional)

  cute af

**Comment by Unthrottled** [comment]
I've wanted to watch this anime for a while now. 
It's currently not on CrunchyRoll :disappointed: 

After I watch it, I might be able to choose best girl. Because creating a theme for all of them is a tall order! I'm just hoping they are not all best girl :sweat_smile:
