### ISSUE TITLE
[Theme Request] Coconut 

### ISSUE THREAD

**Issue by Nightzer** [doki-theme/doki-master-theme#74]
## Who/What do you want to be featured?
[Coconut](https://nekopara.fandom.com/wiki/Coconut) from NekoPara
### What do they look like?
![image](https://user-images.githubusercontent.com/2119954/116314133-5344e100-a774-11eb-9342-c70f0c3d2e83.png)
![image](https://user-images.githubusercontent.com/2119954/116314928-5f7d6e00-a775-11eb-8cc0-a8fc66761050.png)
![image](https://user-images.githubusercontent.com/2119954/116314223-6f488280-a774-11eb-8799-38295fde8683.png)

## What type of theme?

- [ ] Light Theme
- [ ] Dark Theme

## Additional Information (Optional)

Maybe for the light Thme in her normal clothes with `#fbecd9` and `#f5e6fd`
and for the dark theme with the maid dress with `#5d4666` and `#f096f1`

i see someone requested #28 and #27 , this will be a nice addition

**Comment by Unthrottled** [comment]
Ah! I almost forgot about the NekoPara girls (I'll need to watch the anime if it's good). I feel like I need a themed release dedicated to this series. Thanks for the suggestion!

**Comment by Unthrottled** [comment]
@Nightzer If you are still using my themes, then you've got something to look forward to in the coming weeks.

![Screenshot from 2021-07-03 10-44-14](https://user-images.githubusercontent.com/15972415/124359782-0f46e000-dbec-11eb-8e95-c31a5b8d2a41.png)

Her purple color scheme is oh so choice :ok_hand: :100:

**Comment by justalemon** [comment]
Oh yes, beautiful.

**Comment by Nightzer** [comment]
> @Nightzer If you are still using my themes, then you've got something to look forward to in the coming weeks.
> 
> ![Screenshot from 2021-07-03 10-44-14](https://user-images.githubusercontent.com/15972415/124359782-0f46e000-dbec-11eb-8e95-c31a5b8d2a41.png)
> 
> Her purple color scheme is oh so choice 👌 💯

omg looks so awesome, u rcok, im still using ur themes :D u do some amazing work !

**Comment by Unthrottled** [comment]
Thanks for the kind words!

I'll be spending this week pushing these themes out to the billion things I maintain :sweat_smile:

**Comment by Nightzer** [comment]
@Unthrottled  just 1 question, u havent updated the jetbrains pluggin  right?  \ D: /

**Comment by Unthrottled** [comment]
@Nightzer No worries! The plugin update just got approved a few hours ago as well, so there is that as well.
