### ISSUE TITLE
[Theme Request] Shima Rin

### ISSUE THREAD

**Issue by LarveyOfficial** [doki-theme/doki-master-theme#81]
## Who/What do you want to be featured?

Shima Rin From Yuru Camp

### What do they look like?

![image](https://user-images.githubusercontent.com/39219859/120090559-a2fb2d00-c0d1-11eb-8bcb-730df948675b.png)

![image](https://user-images.githubusercontent.com/39219859/120090565-a8587780-c0d1-11eb-95e1-3ed42423668f.png)

## What type of theme?

- [ ] Dark Theme

## Additional Information (Optional)

Color pallet is awesome. Simple, and relaxing character.

**Comment by Unthrottled** [comment]
She's cute! 

I've been debating whether or not to add this anime to my already large watch list.

Thank you for the suggestion!

**Comment by LarveyOfficial** [comment]
@Unthrottled 100% watch it, its by far one maybe even my favorite anime. Super relaxing, great to watch after a long day

**Comment by Unthrottled** [comment]
:thinking: I have a hard decision to make.

Do I references this color palette?

![de4tzs4-c55bcd40-cd4a-4755-9e66-7cd8bdb1893b](https://user-images.githubusercontent.com/15972415/121265577-a2575900-c87e-11eb-9a53-220c66198c8c.jpg)

I guess I would have a [gruvbox](https://github.com/morhetz/gruvbox) looking theme if I did that.

---

Or do I reference this color palette?

![5ed016f97f9eee5bbcebd6c95cd8c419](https://user-images.githubusercontent.com/15972415/121265693-cdda4380-c87e-11eb-9ae8-484b8de4de9d.jpg)

Then I might have a [Nord](https://www.nordtheme.com/ports/jetbrains) looking theme.

Hard choices.

@LarveyOfficial You want to weigh in? I like both.

---

What I do know is that I am pretty sure I am vectorizing the Secret Society BLANKET

![1flrfli3btg01](https://user-images.githubusercontent.com/15972415/121265784-f95d2e00-c87e-11eb-96fa-2b37f73715ef.jpg)

as the background art to be used (or maybe the sticker, I dunno so many choices)

**Comment by Unthrottled** [comment]
I actually think I made up my mind. I think I'll save the next brownish theme for [Chocola](https://github.com/doki-theme/doki-master-theme/issues/27). Sorry about the noise!

**Comment by LarveyOfficial** [comment]
Just noticed this, its been a bit since I checked GitHub, I agree on the saving the Brown for Chocola, I think the Nord or maybe even colors based of the Blanket would make sense. I'm on VSCode So I'm exited to see how it looks

**Comment by Unthrottled** [comment]
![Screenshot from 2021-06-12 11-13-39](https://user-images.githubusercontent.com/15972415/121782507-569efb00-cb6f-11eb-99ae-bfaf95d5ca2e.png)

I took the blue and just ran with it. Is it canon? no. Does it pair well the the look and feel? O ya.

I'll have the VS Code release soon enough. Just got to get done with the other platforms first.

**Comment by LarveyOfficial** [comment]
That looks amazing

**Comment by LarveyOfficial** [comment]
Mega Excited lol

**Comment by Unthrottled** [comment]
@LarveyOfficial  Aight fam, [v13](https://github.com/doki-theme/doki-theme-vscode/releases/tag/v13.0.0) has been published to the marketplace and is available. 

Also thank you for your other theme submissions! I'll keep them in when I am planning future releases :smiley:
