### ISSUE TITLE
[Theme Request] Ralphtalia(The Rising of the Shield Hero)

### ISSUE THREAD

**Issue by luxuriouscoder26** [doki-theme/doki-master-theme#84]
## Who/What do you want to be featured?

[Ralphtalia](https://shield-hero.fandom.com/wiki/Raphtalia) from The Rising of the Shield Hero.

### What do they look like?

![Profile One](https://images-na.ssl-images-amazon.com/images/I/61UM6jyvU1L._AC_SX466_.jpg)

![Profile Two](https://www.anime-planet.com/images/characters/raphtalia-66508.jpg)

![Profile Three](https://ih1.redbubble.net/image.925075790.0300/flat,750x,075,f-pad,750x1000,f8f8f8.jpg)

## What type of theme?

- [x] Light Theme
- [x] Dark Theme

**Comment by Unthrottled** [comment]
I'll eventually have to check this anime out, she's heckin cute!

**Comment by luxuriouscoder26** [comment]
Yes she is
