### ISSUE TITLE
[Theme Request] Cinnamon

### ISSUE THREAD

**Issue by justalemon** [doki-theme/doki-master-theme#99]
## Who/What do you want to be featured?

Cinnamon from Nekopara.

### What do they look like?

![izv4eb6zkq471](https://user-images.githubusercontent.com/11861253/124988767-6abe0700-e00c-11eb-8cbf-9210204627b9.jpg)
![E1tKQIx](https://user-images.githubusercontent.com/11861253/124988771-6d206100-e00c-11eb-92d6-3e778d34150f.jpg)
![nekopara___cinnamon_wallpaper_by_seira_hirano_da1x32t-fullview](https://user-images.githubusercontent.com/11861253/124988853-82958b00-e00c-11eb-958b-400e9e6784a6.png)

## What type of theme?

- [X] Light Theme
- [X] Dark Theme

## Additional Information (Optional)

> Nothing lewd or obscene please!

Cinnamon is the opposite.

Ill try to provide a color palette once I finish my current project.

Also, top tier lewdness waifu.

**Comment by Unthrottled** [comment]
Thanks for the suggestion! I'll consider adding Cinnamon, Azuki, & Maple (perhaps Shigure), after I've played the game or watched the anime. That way I'll see if I want a NekoPara v2 release :)

**Comment by justalemon** [comment]
> Ill try to provide a color palette once I finish my current project.

I tried to submit a theme but was unable to due to `yarn link` not supporting exFAT drives. Sorry about this one!

**Comment by Unthrottled** [comment]
> I tried to submit a theme but was unable to due to yarn link not supporting exFAT drives.

🤔 Hmm, If you are talking about linking the doki-build-source, then you shouldn't need to link, 1.4.0 has the NekoPara grouping meow. 

Anyways, If you are wanting to submit an actual theme, I'll welcome it. However, I do have a vision for the themes, so I hope you'll also be fine with me tweaking it the way I want them to look (the art and colors, and the such) :)

**Comment by justalemon** [comment]
> so I hope you'll also be fine with me tweaking it the way I want them to look (the art and colors, and the such)

Nah, don't worry about it. I do the same with the PRs my projects.

**Comment by justalemon** [comment]
Aight, I give up with trying to make the theme myself. Just in case, this is what I had in mind:

* Light Theme: Light Green Background with Purple Accents
* Dark Theme: Purple Background With Light Green Accents

I managed to get the following colors from an official picture (First one in the issue) that *might* fit this theme, but that is up to you :)

* Green
  * Dark: 418061, 7bbba3
  * Mid: 95d589, 82d881
  * Light: d9f9ad
* Purple
  * Dark: 4d4088
  * Mid: 7c72d3
  * Light: 8685d5, c1b2e9

Green/Purple comes from the Headband/Hair combination when Cinnamon uses the La Soleil uniform.

**Comment by Unthrottled** [comment]
Thank you! 

One of the things that I've realized over time, is that the exact colors that are used on Waifus are bright and vivid, and don't look great as a theme. They look good on the girls tho. Its all about finding balance. I've got an idea as to what her theme should look like. 

BTW, I don't make as many light themes, because I like colorful syntax highlighting. I learned you can't have _readable_ bright pretty colors on light themes 😢 

I also probably use this image as the background if I decide I need some Cinnamon (or some variant of the heart hand pose)

![E1tKQIx](https://user-images.githubusercontent.com/11861253/124988771-6d206100-e00c-11eb-92d6-3e778d34150f.jpg)

**Comment by justalemon** [comment]
> is that the exact colors that are used on Waifus are bright and vivid, and don't look great as a theme

True, but is still possible to use the *base* colors from the character to make a theme (in the case of Cinnamon, purple and green).

> I don't make as many light themes, because I like colorful syntax highlighting. I learned you can't have readable bright pretty colors on light themes

If I'm being honest, I have nothing against light themes but I personally don't like the "White Background with Extra Colors" type of themes. A lighter color is ok in some environments* but pure FFFFFF White Background feels... wrong.

> I also probably use this image as the background if I decide I need some Cinnamon (or some variant of the heart hand pose)

I know that the final decision of the theme is up to you, but I kinda feel that the Hearth Pose is not fit for Cinnamon as a character. That would be a Chocola thing, just like the existing Chocola wallpaper.

One that might be better for Cinnamon is the *two hands in the cheek* pose:

![image](https://user-images.githubusercontent.com/11861253/125110782-0a35d500-e0b3-11eb-8af0-3c6aac98463f.png)

There is also the *hands on top of boobs* pose:

![image](https://user-images.githubusercontent.com/11861253/125111442-e6bf5a00-e0b3-11eb-9192-c1898d9852e8.png)

Or in the extreme cases, the *I am moist* pose:

![image](https://user-images.githubusercontent.com/11861253/125111948-8aa90580-e0b4-11eb-908d-bd1cbea702ac.jpg)

**Comment by Unthrottled** [comment]
I'm just putting this here for later. I like Cinnamon's pose in this one.

![image](https://user-images.githubusercontent.com/15972415/127239601-ff3cbe30-3755-4dda-8f70-98acef86b968.png)

**Comment by Unthrottled** [comment]
@justalemon So I convinced myself that I needed more cat girls. I've made it up to Vol. 3, and I am currently convinced Cinnamon & Maple are the best pair of the bunch. Anyways this is what I got, expect a release in a couple of weeks or so. :+1: 

![Screenshot from 2021-07-30 15-20-37](https://user-images.githubusercontent.com/15972415/127708286-6937f542-670d-4803-b2fa-b438235ab48d.png)

**Comment by justalemon** [comment]
Noice.

Also, no Shigure planned?

**Comment by Unthrottled** [comment]
Yeah, I've got Shigure planned, just under a different release. She'll be in the release themed, "Love me Onii-san!" :joy: . I've tentatively planned: Izumi Sagiri, Kosaka Kirino, & Minaduki Shigure, after the current one I am working on.
